version: '3.1'
#
services:

  base: 
    build: bacula-base/
    image: dividia/bacula-base:11.0.5
#    
  db:
    build: bacula-catalog/
    image: dividia/bacula-catalog:11.0.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bacula
      MYSQL_PASSWORD: bacula
      MYSQL_USER: bacula
      MYSQL_DATABASE: bacula
    # volumes:
    #   - dbdata:/var/lib/mysql/data:rw
    ports:
      - 5432:5432
#
  bacula-dir:
    build: bacula-dir/
    image: dividia/bacula-director:11.0.5
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    depends_on: 
      - db      
    ports:
      - 9101:9101
#
  bacula-sd:
    build: bacula-sd/
    image: dividia/bacula-storage:11.0.5
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9103:9103
#
  bacula-fd:
    build: bacula-fd/
    image: dividia/bacula-client:11.0.5
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9102:9102
#
  baculum-api:
    build: baculum-api/
    image: dividia/baculum-api:11.0.5
    restart: unless-stopped
    depends_on: 
      - db
      - bacula-dir
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9096:9096

#
  baculum-web:
    build: baculum-web/
    image: dividia/baculum-web:11.0.5
    restart: unless-stopped
    depends_on: 
      - baculum-api
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9095:9095

# 
#volumes: 
#  dbdata:
#
#  gmail:
#    image: fametec/postfix:gmail
#    restart: unless-stopped
#    depends_on:
#      - bacula-dir
#    # ports:
#    #  - 30025:25
#    environment:
#      GMAIL_USER: xxxxxxxx
#      GMAIL_PASS: xxxxxxxx
#
#  smtp2tg:
#    image: b3vis/docker-smtp2tg
#    restart: unless-stopped
#    volumes:
#      - ./etc/smtp2tg.toml:/config/smtp2tg.toml:ro
#    #    ports:
#    #  - "31025:25"
#    depends_on:
#      - bacula-dir
#
# 
#volumes: 
#  dbdata:
